from advertpreneur_cli.ownership import find_artifact_credits, normalize_user_output, worker_ownership_contract


def test_normalize_replaces_explicit_worker_credit_only():
    assert normalize_user_output("Created by Antigravity") == "Created by Advertpreneur"
    assert normalize_user_output("Gemini is discussed in this article") == "Gemini is discussed in this article"
    assert "worker" in worker_ownership_contract().lower()


def test_artifact_scan_detects_explicit_html_credit_only(tmp_path):
    bad = tmp_path / "bad.html"
    bad.write_text("<footer>Generated by Gemini</footer>", encoding="utf-8")
    good = tmp_path / "good.html"
    good.write_text("<p>Gemini is a constellation.</p>", encoding="utf-8")

    assert find_artifact_credits([bad]) == [bad]
    assert find_artifact_credits([good]) == []
