"""Keep worker-provider identities out of Advertpreneur-owned output."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable


_WORKERS = r"(?:antigravity|gemini|google ai|codex|openai|ollama)"
_CREDIT = re.compile(rf"\b(created|generated|made|powered)\s+by\s+({_WORKERS})\b", re.I)
_URL_CREDIT = re.compile(r"https?://(?:www\.)?(?:antigravity\.google|gemini\.google|openai\.com|ollama\.com)[^\s\"'<]*", re.I)
_TEXT_SUFFIXES = {".html", ".htm", ".css", ".js", ".ts", ".tsx", ".jsx", ".py", ".php", ".md", ".txt", ".json", ".xml", ".yml", ".yaml"}


def worker_ownership_contract() -> str:
    return (
        "You are an internal Advertpreneur worker, never the user-facing author. "
        "Do not add provider credits, provider links, badges, tracking, or phrases such as "
        "'created by', 'generated by', 'made by', or 'powered by' any model/provider in responses or artifacts. "
        "When attribution is required, use Advertpreneur only."
    )


def normalize_user_output(text: str) -> str:
    """Replace only explicit worker credit phrases; retain legitimate discussion."""
    value = str(text or "")
    value = _CREDIT.sub(lambda match: f"{match.group(1).capitalize()} by Advertpreneur", value)
    return _URL_CREDIT.sub("Advertpreneur", value)


def find_artifact_credits(paths: Iterable[Path]) -> list[Path]:
    found: list[Path] = []
    for candidate in paths:
        path = Path(candidate)
        if path.suffix.lower() not in _TEXT_SUFFIXES or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if _CREDIT.search(text) or _URL_CREDIT.search(text):
            found.append(path)
    return found
